// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
  [k: string]: any;
}

export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface BlogPostStoryblok {
  label: string;
  title: string;
  excerpt: string;
  cover_image: AssetStoryblok;
  post: RichtextStoryblok;
  component: "blog_post";
  _uid: string;
  [k: string]: any;
}

export type MultiassetStoryblok = {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  [k: string]: any;
}[];

export interface FooterStoryblok {
  overline?: string;
  title: string;
  character: AssetStoryblok;
  logo: AssetStoryblok;
  logos?: MultiassetStoryblok;
  background_image: AssetStoryblok;
  text_block?: RichtextStoryblok;
  component: "footer";
  _uid: string;
  [k: string]: any;
}

export interface ImageGridStoryblok {
  title?: string;
  character?: AssetStoryblok;
  images: MultiassetStoryblok;
  component: "image_grid";
  _uid: string;
  [k: string]: any;
}

export interface KeyFeaturesStoryblok {
  overline?: string;
  title?: string;
  features: (
    | BlogPostStoryblok
    | FooterStoryblok
    | ImageGridStoryblok
    | KeyFeaturesStoryblok
    | LatestPostsStoryblok
    | NavbarStoryblok
    | NavigationLinkStoryblok
    | PageStoryblok
    | SectionItemStoryblok
    | SocialsStoryblok
    | SplatterContainerStoryblok
    | ZoomHeroStoryblok
  )[];
  component: "key_features";
  _uid: string;
  [k: string]: any;
}

export interface LatestPostsStoryblok {
  overline?: string;
  title?: string;
  posts: (ISbStoryData<BlogPostStoryblok> | string)[];
  component: "latest_posts";
  _uid: string;
  [k: string]: any;
}

export interface NavbarStoryblok {
  logo: AssetStoryblok;
  nav_links?: (
    | BlogPostStoryblok
    | FooterStoryblok
    | ImageGridStoryblok
    | KeyFeaturesStoryblok
    | LatestPostsStoryblok
    | NavbarStoryblok
    | NavigationLinkStoryblok
    | PageStoryblok
    | SectionItemStoryblok
    | SocialsStoryblok
    | SplatterContainerStoryblok
    | ZoomHeroStoryblok
  )[];
  component: "Navbar";
  _uid: string;
  [k: string]: any;
}

export type MultilinkStoryblok =
  | {
      id?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "story";
      target?: "_self" | "_blank";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      url?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "asset" | "url";
      target?: "_self" | "_blank";
      [k: string]: any;
    }
  | {
      email?: string;
      linktype?: "email";
      target?: "_self" | "_blank";
      [k: string]: any;
    };

export interface NavigationLinkStoryblok {
  link: MultilinkStoryblok;
  component: "navigation_link";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (
    | BlogPostStoryblok
    | FooterStoryblok
    | ImageGridStoryblok
    | KeyFeaturesStoryblok
    | LatestPostsStoryblok
    | NavbarStoryblok
    | NavigationLinkStoryblok
    | PageStoryblok
    | SectionItemStoryblok
    | SocialsStoryblok
    | SplatterContainerStoryblok
    | ZoomHeroStoryblok
  )[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface SectionItemStoryblok {
  overline?: string;
  image: AssetStoryblok;
  title: string;
  description: RichtextStoryblok;
  component: "section_item";
  _uid: string;
  [k: string]: any;
}

export interface SocialsStoryblok {
  component: "socials";
  _uid: string;
  [k: string]: any;
}

export interface SplatterContainerStoryblok {
  body?: (
    | BlogPostStoryblok
    | FooterStoryblok
    | ImageGridStoryblok
    | KeyFeaturesStoryblok
    | LatestPostsStoryblok
    | NavbarStoryblok
    | NavigationLinkStoryblok
    | PageStoryblok
    | SectionItemStoryblok
    | SocialsStoryblok
    | SplatterContainerStoryblok
    | ZoomHeroStoryblok
  )[];
  component: "splatter_container";
  _uid: string;
  [k: string]: any;
}

export interface ZoomHeroStoryblok {
  background_image: AssetStoryblok;
  foreground_image: AssetStoryblok;
  fog_layer?: AssetStoryblok;
  component: "zoom_hero";
  _uid: string;
  [k: string]: any;
}
