// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface FooterStoryblok {
  component: "footer";
  _uid: string;
  [k: string]: any;
}

export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
  [k: string]: any;
}

export type MultiassetStoryblok = {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  [k: string]: any;
}[];

export interface ImageGridStoryblok {
  title?: string;
  character?: AssetStoryblok;
  images: MultiassetStoryblok;
  component: "image_grid";
  _uid: string;
  [k: string]: any;
}

export interface KeyFeaturesStoryblok {
  overline?: string;
  title?: string;
  features: (FooterStoryblok | ImageGridStoryblok | KeyFeaturesStoryblok | PageStoryblok | SectionItemStoryblok)[];
  component: "key_features";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (FooterStoryblok | ImageGridStoryblok | KeyFeaturesStoryblok | PageStoryblok | SectionItemStoryblok)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface SectionItemStoryblok {
  overline?: string;
  image: AssetStoryblok;
  title: string;
  description: RichtextStoryblok;
  component: "section_item";
  _uid: string;
  [k: string]: any;
}
